version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: finance_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: